### ISSUE TITLE
Filter funktioniert nicht bei Uhrzeiten mit Zulu Offset

### ISSUE THREAD

**Issue by scjminova** [minova-afis/aero.minova.fuelportal.pwa#13]
**Beschreibung:**

ALS: Developer
MÖCHTE ICH: Dass der Filter für die Volltextsuche auf bei Uhrzeiten funktioniert
SO DASS: Die User auch nach der Uhrzeit filtern können

Abrechnung={XXX/XXX/XXX/ZWARTUNG}

**Comment by CE7** [comment]
Hier bitte nochmal mit KAU sprechen, damit wir es wie auch beim alten Fuel-Portal machen.
